# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addmsgUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(416, 165)
        self.msg = QtWidgets.QTextEdit(Form)
        self.msg.setGeometry(QtCore.QRect(40, 40, 331, 74))
        self.msg.setObjectName("msg")
        self.ensure = QtWidgets.QPushButton(Form)
        self.ensure.setGeometry(QtCore.QRect(299, 130, 71, 32))
        self.ensure.setObjectName("ensure")
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setGeometry(QtCore.QRect(210, 130, 71, 32))
        self.cancel.setObjectName("cancel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.msg.setPlaceholderText(_translate("Form", "在这里输入你的留言"))
        self.ensure.setText(_translate("Form", "提交"))
        self.cancel.setText(_translate("Form", "取消"))
