# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwinUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(525, 426)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 20, 381, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(140, 20, 101, 100))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.test1 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.test1.setObjectName("test1")
        self.verticalLayout_2.addWidget(self.test1)
        self.test2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.test2.setObjectName("test2")
        self.verticalLayout_2.addWidget(self.test2)
        self.showmsg = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.showmsg.setObjectName("showmsg")
        self.verticalLayout_2.addWidget(self.showmsg)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(140, 20, 101, 100))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addmsg = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.addmsg.setObjectName("addmsg")
        self.verticalLayout_3.addWidget(self.addmsg)
        self.logout = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.logout.setObjectName("logout")
        self.verticalLayout_3.addWidget(self.logout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(140, 19, 102, 100))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.alterfee = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.alterfee.setObjectName("alterfee")
        self.verticalLayout_4.addWidget(self.alterfee)
        self.test4 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.test4.setObjectName("test4")
        self.verticalLayout_4.addWidget(self.test4)
        self.showman = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.showman.setObjectName("showman")
        self.verticalLayout_4.addWidget(self.showman)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", "所有用户"))
        self.test1.setText(_translate("Form", "登陆"))
        self.test2.setText(_translate("Form", "注册"))
        self.showmsg.setText(_translate("Form", "查看留言"))
        self.groupBox.setTitle(_translate("Form", "一般用户"))
        self.addmsg.setText(_translate("Form", "提交留言"))
        self.logout.setText(_translate("Form", "登出"))
        self.groupBox_2.setTitle(_translate("Form", "管理员"))
        self.alterfee.setText(_translate("Form", "修改物业费"))
        self.test4.setText(_translate("Form", "更改信息"))
        self.showman.setText(_translate("Form", "显示人员"))
