# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwinUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.test1 = QtWidgets.QPushButton(Form)
        self.test1.setGeometry(QtCore.QRect(40, 30, 100, 32))
        self.test1.setObjectName("test1")
        self.test2 = QtWidgets.QPushButton(Form)
        self.test2.setGeometry(QtCore.QRect(40, 80, 100, 32))
        self.test2.setObjectName("test2")
        self.test3 = QtWidgets.QPushButton(Form)
        self.test3.setGeometry(QtCore.QRect(40, 120, 100, 32))
        self.test3.setObjectName("test3")
        self.test4 = QtWidgets.QPushButton(Form)
        self.test4.setGeometry(QtCore.QRect(40, 160, 100, 32))
        self.test4.setObjectName("test4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.test1.setText(_translate("Form", "PushButton"))
        self.test2.setText(_translate("Form", "PushButton"))
        self.test3.setText(_translate("Form", "PushButton"))
        self.test4.setText(_translate("Form", "PushButton"))
