# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'queryfeeUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        Form.setMaximumSize(QtCore.QSize(400, 300))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 10, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.house_id = QtWidgets.QLineEdit(Form)
        self.house_id.setGeometry(QtCore.QRect(130, 50, 113, 21))
        self.house_id.setObjectName("house_id")
        self.display = QtWidgets.QTextBrowser(Form)
        self.display.setGeometry(QtCore.QRect(70, 120, 256, 171))
        self.display.setObjectName("display")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 100, 61, 16))
        self.label_2.setObjectName("label_2")
        self.ensure = QtWidgets.QPushButton(Form)
        self.ensure.setGeometry(QtCore.QRect(260, 50, 51, 32))
        self.ensure.setObjectName("ensure")
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setGeometry(QtCore.QRect(260, 80, 51, 32))
        self.cancel.setObjectName("cancel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "输入你要查询的编号 :"))
        self.label_2.setText(_translate("Form", "查询所得 :"))
        self.ensure.setText(_translate("Form", "确定"))
        self.cancel.setText(_translate("Form", "取消"))
